[hetzner_backup]
type = sftp
host = u547846.your-storagebox.de
user = u547846
port = 23
key_file = ~/.ssh/id_ed25519
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

[hetzner-crypt]
type = crypt
remote = hetzner_backup:encrypted
password = Pb1d9kQ0K5Ls-otXC6Wi-akvDMcYB8k7tfhRlsYpXPpDVkbaEcw
password2 = dwoK5wxET1sQgwlaZVWTNy8MTghcbF1cABxYCr930zzwzBRyXqg
